resource.AddFile("materials/vgui/icon_soap.vmt")
resource.AddFile("materials/vgui/marker_vision/soap.vmt")
resource.AddFile("sound/soap/slip.wav")
resource.AddFile("models/soap.dx90.vtx")
resource.AddFile("models/soap.mdl")
resource.AddFile("models/soap.phy")
resource.AddFile("models/soap.vvd")
resource.AddFile("materials/models/soap.vmt")
