name: CI

env:
  GLUALINT_VERSION: 1.29.0
  NEODOC_VERSION: 0.2.0
  STYLUA_VERSION: 2.0.0

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download & extract glualint
        run: |
          wget -c https://github.com/FPtje/GLuaFixer/releases/download/${GLUALINT_VERSION}/glualint-${GLUALINT_VERSION}-x86_64-linux.zip -O glualint.zip
          unzip -u glualint.zip
          rm glualint.zip

      - name: Check code with glualint
        run: ./glualint .

  style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ env.STYLUA_VERSION }}
          args: --check .

  doc-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        run: sudo apt-get install -y mono-complete

      - name: Download & extract neodoc
        run: |
          wget -c https://github.com/TTT-2/NeoDoc/releases/download/v${NEODOC_VERSION}/NeoDoc-v${NEODOC_VERSION}.zip -O neodoc.zip
          unzip -u neodoc.zip
          rm neodoc.zip

      - name: Check code with neodoc
        run: mono NeoDoc.exe .
